# Generated by Django 2.2.6 on 2020-06-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('mother_name', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('nid', models.IntegerField(blank=True, default=0, null=True)),
                ('member_id', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=200, null=True)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu')], max_length=200, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('present_address', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('relation', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('nominee_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('nominee_marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=200, null=True)),
                ('nominee_religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu')], max_length=200, null=True)),
                ('nominee_nid', models.IntegerField(blank=True, default=0, null=True)),
                ('nominee_present_address', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('account_no', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000, null=True)),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Amount')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
    ]
