# Generated by Django 2.2.6 on 2020-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deposite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='diposite_pic',
            field=models.ImageField(blank=True, default='diposite.jpg', null=True, upload_to=''),
        ),
    ]
