# Generated by Django 2.2.6 on 2020-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201219_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
