# Generated by Django 2.2.6 on 2020-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201219_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nominee_name',
            field=models.CharField(max_length=200),
        ),
    ]
