# Generated by Django 2.2.6 on 2020-12-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201219_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nominee_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
