# Generated by Django 2.2.6 on 2020-12-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201230_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='username',
        ),
    ]
