# Generated by Django 2.2.6 on 2020-12-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201230_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='last_name',
        ),
    ]
